#!/bin/bash

if [ -z "$*" ]; then
	echo "Usage:"
	echo ""
	echo "$0 [PNG files]"
	exit 1
fi

TMP=$(mktemp -d)

mkdir "$TMP/suspicious"
echo Storing suspicious files in "$TMP/suspicious"

for f in "$@"; do
	convert -strip -flatten "$f" "$TMP/_flat.bmp"
	convert -strip -background black -flatten "$f" "$TMP/_flat-black.bmp"
	convert -strip -alpha off -flatten "$f" "$TMP/_alphaoff.bmp"
	if ! cmp -s "$TMP/_flat.bmp" "$TMP/_alphaoff.bmp" && ! cmp -s "$TMP/_flat-black.bmp" "$TMP/_alphaoff.bmp"
	then
		echo "$f looks suspicious"
		cp "$f" "$TMP/suspicious/"
		convert "$TMP/_alphaoff.bmp" "$TMP/suspicious/$(basename "$f").noalpha.png"
	fi
done

echo Please inspect files in "$TMP/suspicious"
