#!/bin/bash

if [ -z "$*" ]; then
	echo "Usage:"
	echo ""
	echo "$0 [PNG files]"
	exit 1
fi

TMP=$(mktemp -d)

mkdir "$TMP/suspicious"

susp=0
for f in "$@"; do
	convert "$f" -strip -alpha extract "$TMP/_out.rgb"

	if ! (hexdump -ve '"%.2x"' "$TMP/_out.rgb"|grep -q '^f*$'); then
		echo "$f suspicious"
		cp "$f" "$TMP/suspicious/"
		convert -strip -alpha off "$f" "$TMP/suspicious/$(basename "$f").noalpha.png"
		susp=1
	fi
done

if [ $susp -eq 1 ]; then
	echo Please inspect files in "$TMP/suspicious"
else
	echo No suspicious files
fi
